_project_root/_project_site/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls import url,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^about/$',views.about),
    url(r'^$',views.home),
    url(r'^blog/',include('blog.urls')),
    path(r'calendar/',include('events.urls')),
    url(r'^accounts/',include('account.urls'))
   
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

_project_root/account/urls.py
from django.conf.urls import url
from . import views

app_name = 'account'

urlpatterns = [
    url(r'^signup/$',views.signup_view,name = 'signup'),
    url(r'^login/$',views.login_view,name = 'login'),
    url(r'^logout/$',views.logout_view,name = 'logout'),
    ]

_project_root/blog/urls.py
from django.conf.urls import url
from django.urls import include,path
from django.contrib import admin
from . import views

app_name = 'blog'

urlpatterns =[
    #url(r'^blog/',admin.site.urls),

    #both two ways below can call html correctly
    #path('',views.blog_list,name ='blog_list' ),
    url(r'^$',views.blog_list,name ='list'),
    url(r'^create/$',views.blog_create, name = 'create'),
    url(r'^(?P<slug>[\w-]+)/$',views.blog_detail,name='detail'),
    
    
    ]

_project_root/events/urls.py
from django.urls import path, re_path
from . import views
 
urlpatterns = [
    #path('<int:year>/<str:month>/', views.index, name='index'),
    path('',views.index, name='index'),
    re_path(r'^(?P<year>[0-9]{4})/(?P<month>0?[1-9]|1[0-2])/',views.index,name = 'index'),
]

_project_root/account/models.py
from django.db import models

# Create your models here.

_project_root/blog/models.py
from django.db import models
from django.contrib.auth.models import User

class myBlog(models.Model):
    title = models.CharField(max_length = 100)
    slug  = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    thumb = models.ImageField(default = 'default.png',blank = True)
    author = models.ForeignKey(User, default = None, on_delete=models.CASCADE,)


def __str__(self):
    return self.title


#def snippet(self):
    #limit the words
    #return self.body[0:30]

# Create your models here.

_project_root/events/models.py
from django.db import models
from django.contrib.auth.models import User

class Venue(models.Model):
    name = models.CharField('Venue Name', max_length=120)
    address = models.CharField(max_length=300)
    zip_code = models.CharField('Zip/Post Code', max_length=12)
    phone = models.CharField('Contact Phone', max_length=20, blank = True)
    web = models.URLField('Web Address',blank = True)
    email_address = models.EmailField('Email Address', blank = True)
 
    def __str__(self):
       return self.name
 
 
class MyclubUser(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField('User Email')

    def __str__(self):
        return self.first_name + " " + self.last_name

class Event(models.Model):
    name = models.CharField('Event Name',max_length = 120)
    event_date = models.DateTimeField('Event Date')
    venue = models.CharField(max_length = 120)
    manager = models.ForeignKey(User, blank= True,null=True,on_delete=models.SET_NULL)
    #models.CharField(max_length = 60)
    description = models.TextField(blank = True)

_project_root/blog/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.myBlog
        fields =['title','body','slug','thumb']
        

_project_root/_project_site/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return render(request,'home.html')


def about(request):
    return render(request,'about.html')

_project_root/account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        
        if form.is_valid():
            user = form.save()
            login(request,user)
            #log in
            return redirect('blog:list')
        
    else:
        form = UserCreationForm()
            

    return render(request,'account/signup.html',{'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        
        if form.is_valid():
            #login
            user = form.get_user()
            login(request,user)
            
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('blog:list')
            
            #return redirect('blog:list')

    else:
        form = AuthenticationForm()

    return render(request, 'account/login.html',{'form':form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
    return redirect('blog:list')



    

_project_root/blog/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import myBlog
from django.contrib.auth.decorators import login_required
from . import forms

def blog_list(request):
    blogs = myBlog.objects.all().order_by('date')
    return render(request,'blog/blog_list.html',{'blogs':blogs})

def blog_detail(request,slug):
    #return HttpResponse(slug)
    myblog = myBlog.objects.get(slug=slug)
    return render(request,'blog/blog_detail.html',{'myblog':myblog})

@login_required(login_url = '/accounts/login/')
def blog_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            #save article to database
            ins = form.save(commit=False)
            ins.author = request.user
            ins.save()
            return redirect('blog:list')
    else:
        form = forms.CreateArticle()
    return render(request,'blog/blog_create.html',{'form':form})

# Create your views here.

_project_root/events/views.py
from django.shortcuts import render
#from django.http import HttpResponse
from datetime import date
import calendar
from calendar import HTMLCalendar


def index(request,year = date.today().year,month = date.today().month):
    #try1
    #t = date.today()
    #month = date.strftime(t,'%b')
    #year = t.year


    year = int(year)
    month = int(month)
    if year < 1900 or year > 2099:
        year = date.today().year
    month_name = calendar.month_name[month]
    
    title = "MyClub Event Calendar - %s %s" % (month_name,year)
    cal = HTMLCalendar().formatmonth(year,month)
    #return HttpResponse("<h1>%s</h1><p>%s</p>" % (title,cal))
    return render(request,'events/calendar_base.html',{'title':title,'cal':cal})

_project_root/_project_site/templates/base.html
{% load static %}
<!doctype html>
<html>

<head>
    <meta charset="utf-8">

    <title>
        {% block title %}
        {{ page_title|default:"Untitled Page" }}
        {% endblock title %}
    </title>

    <link href="{% static 'main.css' %}" rel="stylesheet" e="text/css">
</head>

<body>
    <div id="wrapper">

        <header id="header">
            <div id="logo"><img src="{% static 'logo.png' %}" alt="" /></div>
            <div id="top_menu">Home | Calendar | About | Contact</div>
            <div id="topbanner"><img src="{% static 'top_banner.png' %}" alt="" /></div>
        </header>

        <aside id="rightsidebar">

            <nav id="nav">
                <ul>
                    <li>Menu 1</li>
                    <li>Menu 2</li>
                    <li>Menu 3</li>
                </ul>
            </nav>

        </aside>
        <section id="main">
            {% block content %}
            <p>Placeholder text in base template. Replace with page content.</p>
            {% endblock content %}
        </section>
        <footer id="footer">Copyright &copy;
            <script type="text/JavaScript">
                document.write(new Date().getFullYear());                    
            </script> MyClub
        </footer>
    </div>
</body>

</html>

_project_root/_project_site/templates/base_html.html
{% load static from staticfiles %}


<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>
            Blog
        </title>
        <link href="{% static 'blog_list.css' %}" rel="stylesheet" e="text/css">
    </head>
    <body>
        <div class = "wrapper">
            <h1><a href="{% url 'blog:list' %}"><img src="{% static 'logo.png' %}"/></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class = "logout_link" action = "{% url 'account:logout' %}" method = "POST">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'blog:create' %}">New Blog</a></li>
                    {% else %}
                    <li> <a href="{% url 'account:login' %}">Login</a></li>
                    <li><a href="{% url 'account:signup' %}">Sign up</a></li>
                    {% endif %}
                </ul>
            </nav>
            {% block content %}
            {% endblock %}

        </div>
    </body>
</html>

_project_root/_project_site/templates/home.html
{% load static %}
<!doctype html>
<html>
      <meta charset = "utf-8">
      <head>
            <title>
                  MAY'S WEBSITE
            </title>
      </head>
      <link href="{% static 'home.css' %}" rel="stylesheet" e="text/css">

      <body>
            <div id = "wrapper">
                  <div id = "paragraph">
                        -Some Questions Related To My First Year Study-
                  </div>   
                  <img src="{% static 'top_banner.png' %}" alt="" />
                  <img src="{% static 'banner.png' %}" alt="" />
                  <img src="{% static 'top_banner.png' %}" alt="" />
                  <img src="{% static 'banner.png' %}" alt="" /> 
                  <img src="{% static 'top_banner.png' %}" alt="" />  
                  <img src="{% static 'banner.png' %}" alt="" /> 
                  
                  <div id = "list">
                        <li>What I have enjoyed study this year?</li>
                        <p>
                               This year I started my first year computer science studying. 
                              I experienced many interesting lessons, such as programming in java,
                               artificial intelligence etc. Artificial intelligence is the most amazing module for me. 
                               During the lectures and labs, I learnt many useful knowledge like algorithms,
                                which would in really helpful in future learning. 
                        </p>
                        <li>What I am looking forward to learn about in next academic year?</li>
                        <p>
                              In the upcoming year, the most attracting module for me is programming in C\C++.
                               I believe learning more languages could help me build better programming skill. 
                               Meanwhile, I am really interested in Artificial Intelligence module in year 2. 
                               It could bring interesting labs and more amazing algorithms. 
                        </p>
                        <li>Bridging coursework: How Django works?</li>
                        <p>
                              At the start of building a website, I need to create a virtual environment,
                               and upload all the tools I need, for example Django and python.Then,
                                I begin to write views and html file, and import them to the url file.
                                 After that, I had my first webpage, which is called home. 
                                 If I want my webpage be more beautiful, 
                                 I would create CSS file to make webpage exactly like what I expected. 
                              However, the functions of my website may be too simple, 
                              therefore I need to create apps to complete other function.
                               Firstly, we need to use command prompt to create a new app. 
                               We may need to store some data, so we make changes in models.py.
                                Subsequently, we will see data names in admin website. 
                                Following by that is entirely what I did at the first.
                              
                               
                        </p>
                        <li><a href = "http://127.0.0.1:8000/blog/">Do You Wannna Try My Blog? Click Me!</a></li>
                  </div>

            </div>
      </body>



</html>

_project_root/blog/templates/blog/blog_create.html
{% extends 'base_html.html' %}

{% block content %}
<div class="create-blog">
    <h2>
        Create A New Article
    </h2>
    <form class="site_form" action="{% url 'blog:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value = "Create">
    </form>
</div>

{% endblock %}

_project_root/blog/templates/blog/blog_detail.html
{% extends 'base_html.html' %}

{% block content %}
<div class = "blog-detail">
    <div class = "blog">
        <img src = "{{myblog.thumb.url}}"/>

        <h2>{{myblog.title}}</h2>
        <p>{{myblog.body}}</p>
        <p>{{myblog.date}}</p>
    </div>
</div>


{% endblock %}

_project_root/blog/templates/blog/blog_list.html
{% extends 'base_html.html' %}

{% block content %}
        <div id = "head">
            <h1> Blog List</h1>
        </div>   
        <div class = "blogs">
            {% for blog in blogs%}
            <div class ="myblog">
                <h2><a href = "{% url 'blog:detail' slug=blog.slug %}">{{blog.title}}</a> </h2>
                <p>{{blog.body|truncatewords_html:10}}</p>
                <p>{{blog.date}}</p>
            </div>

            {% endfor %}
        </div>

{% endblock %}
   

_project_root/events/templates/events/calendar_base.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
       <h1>{{ title }}</h1>
       <p>{% autoescape off %}{{ cal }}{% endautoescape %}</p>
{% endblock content %}